@CertificateService_HostAddress = http://localhost:8008
@Gateway_HostAddress = http://localhost:5000
@AuthToken = your-jwt-token-here
@certificateId = 6f3ca087-60ce-4a0f-a2b6-220921bf0ece

### Issue a Certificate
# Access: Admin or Instructor
POST {{CertificateService_HostAddress}}/api/certificates/issue
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "studentId": "9f2a2336-b4fe-42d5-ba06-8bc934d05c49",
  "courseId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
}

### Get My Certificates
# Access: Student
GET {{CertificateService_HostAddress}}/api/certificates/student
Authorization: Bearer {{AuthToken}}

### Get Certificate Details
# Access: Student (Own) or Admin
GET {{CertificateService_HostAddress}}/api/certificates/{{certificateId}}
Authorization: Bearer {{AuthToken}}

### Verify a Certificate
# Access: Anonymous
GET {{CertificateService_HostAddress}}/api/certificates/verify/CERT-C281484017944BCA
