@AssessmentService_HostAddress = http://localhost:8007
@Gateway_HostAddress = http://localhost:5000
@AuthToken = your-jwt-token-here
@quizId = 4b08de8b-8a02-4016-a947-aa3674c75005

### Create a Quiz
# Access: Admin or Instructor
POST {{AssessmentService_HostAddress}}/api/assessments
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "courseId": "d7826501-3c46-42c3-a3cc-1113960a1532",
  "title": "Java Basic Quiz",
  "description": "Test your knowledge on java architecture",
  "passingScore": 60
}

### Add a Question to Quiz
# Access: Admin or Instructor
POST {{AssessmentService_HostAddress}}/api/assessments/{{quizId}}/questions
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "text": "what is jdk",
  "options": ["java development kit", "java dev kit", "java default key", "none of the above"],
  "correctOptionIndex": 1
}

### Get Quizzes for a Course uisng course id
# Access: Anyone (Authorized)
GET {{AssessmentService_HostAddress}}/api/assessments/course/d7826501-3c46-42c3-a3cc-1113960a1532
Authorization: Bearer {{AuthToken}}

### Get Quiz Questions (Start Quiz)
# Access: Anyone (Authorized)
GET {{AssessmentService_HostAddress}}/api/assessments/{{quizId}}
Authorization: Bearer {{AuthToken}}

### Submit Quiz Answers
# Access: Student
POST {{AssessmentService_HostAddress}}/api/assessments/{{quizId}}/submit
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "answers": [1]
}
